QAWebsite/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QAWebsite.Data;
using QAWebsite.Models.UserModels;
using QAWebsite.Services;

namespace QAWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAchievementDistributor _achievementDistributor;
        private readonly RatingController _ratingController;
        private readonly QuestionController _questionController;

        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IAchievementDistributor achievementDistributor, DbContextOptions<ApplicationDbContext> dbContextOptions)
        {
            _context = context;
            _userManager = userManager;
            _achievementDistributor = achievementDistributor;
            _ratingController = new RatingController(context, userManager, dbContextOptions);
            _questionController = new QuestionController(context, userManager, achievementDistributor, dbContextOptions);
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_questionController.GetQuestionList(_questionController.GetQuestionQueryable().Take(10)));
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [Route("404")]
        public IActionResult Error()
        {
            return View();
        }
    }
}

QAWebsite/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QAWebsite.Data;
using QAWebsite.Models.Enums;
using QAWebsite.Models.QuestionModels;
using QAWebsite.Models.QuestionViewModels;
using QAWebsite.Models.UserModels;
using QAWebsite.Services;

namespace QAWebsite.Controllers
{
    [Authorize]
    public class QuestionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ApplicationDbContext _extraContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAchievementDistributor _achievementDistributor;
        private readonly TagController _tagController;
        private readonly RatingController _ratingController;
        private readonly AnswerController _answerController;
        private readonly CommentController _commentController;

        public QuestionController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IAchievementDistributor achievementDistributor, DbContextOptions<ApplicationDbContext> dbContextOptions)
        {
            _context = context;
            _extraContext = new ApplicationDbContext(dbContextOptions);
            _userManager = userManager;
            _achievementDistributor = achievementDistributor;
            _tagController = new TagController(context);
            _ratingController = new RatingController(context, userManager, dbContextOptions);
            _answerController = new AnswerController(context, userManager, achievementDistributor, dbContextOptions);
            _commentController = new CommentController(context, userManager, achievementDistributor, dbContextOptions);
        }

        public IQueryable<Question> GetQuestionQueryable()
        {
            return _context.Question
                .Include(x => x.Author)
                .Include(x => x.QuestionTags)
                .ThenInclude(x => x.Tag);
        }

        public IEnumerable<IndexViewModel> GetQuestionList(IEnumerable<Question> query)
        {
            return query.AsEnumerable().Select(q => new IndexViewModel(q,
                    _ratingController.GetRating<QuestionRating>(q.Id),
                    _extraContext.Answer.Count(a => a.QuestionId == q.Id),
                    _extraContext.Flag.Count(f => f.QuestionId == q.Id)))
                .OrderByDescending(q => q.CreationDate).ToList();
        }

        // GET: Question
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(GetQuestionList(GetQuestionQueryable()));
        }

        [AllowAnonymous]
        public IActionResult Search(string search)
        {
            if (search == null)
                return RedirectToAction("Index");

            var split = search.Trim().Normalize().Split(' ');

            var questions = GetQuestionQueryable()
                .AsEnumerable(); //TODO remove in Core 2.1

            var questionAnswers = _extraContext.Answer.Where(a => split.Any(s => a.Content.Normalize().Contains(s))).Select(a => a.QuestionId).Distinct();

            questions = questions.Where(x => questionAnswers.Any(q => q == x.Id) ||
                            split.Any(s => x.Title.Normalize().Contains(s) ||
                                x.Content.Normalize().Contains(s) ||
                                x.QuestionTags.Any(qt => qt.Tag.Name.Normalize().Contains(s)) ||
                                s == x.Author.UserName.Normalize()));

            return View("Index", GetQuestionList(questions));
        }

        [AllowAnonymous]
        public IActionResult SearchByTag(string tag)
        {
            return View("Index", GetQuestionList(GetQuestionQueryable().Where(q => q.QuestionTags.Any(qt => qt.Tag.Name == tag))));
        }

        public async Task<DetailsViewModel> GetDetailsViewModel(string questionId)
        {
            if (questionId == null)
            {
                return null;
            }

            var question = await _context.Question
                .Include(x => x.QuestionTags)
                .ThenInclude(x => x.Tag)
                .SingleOrDefaultAsync(m => m.Id == questionId);
            if (question == null)
            {
                return null;
            }
            var avm = _answerController.GetAnswerList(questionId);
            var cvm = _commentController.GetComments<QuestionComment>(questionId);

            return new DetailsViewModel(question, 
                _context.Users.Where(u => u.Id == question.AuthorId).Select(x => x.UserName).SingleOrDefault(),
                _ratingController.GetRating<QuestionRating>(question.Id),
                _context.Flag.Count(f => f.QuestionId == questionId),
                avm, cvm);
        }

        // GET: Question/Details/5
        [AllowAnonymous]
        [Route("/Question/{id:length(8)}")]
        public async Task<IActionResult> Details(string id)
        {
            var vm = await GetDetailsViewModel(id);

            if (vm == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Question/Create
        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        // POST: Question/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateViewModel vm)
        {
            //Validate here
            var tagNames = _tagController.ValidateParseTags(vm.Tags, ModelState);

            if (_context.Question.Any(x => x.Title == vm.Title.Trim()))
            {
                ModelState.AddModelError("Title", "A question with that title already exists");
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var question = new Question
            {
                Id = Guid.NewGuid().ToString().Substring(0, 8),
                Title = vm.Title.Trim(),
                Content = vm.Content.Trim(),
                CreationDate = DateTime.Now,
                EditDate = DateTime.Now,
                AuthorId = _userManager.GetUserId(User)
            };

            var edit = new QuestionEdit
            {
                Id = Guid.NewGuid().ToString(),
                QuestionId = question.Id,
                EditorId = question.AuthorId,
                NewTitle = question.Title,
                NewContent = question.Content,
                EditDate = question.EditDate
            };
                
            var q = _context.Add(question);
            _context.Add(edit);
            await _context.SaveChangesAsync();

            await _tagController.CreateQuestionTags(question, tagNames);
            _achievementDistributor.check(question.AuthorId, _context, AchievementType.QuestionCreation);
            return RedirectToAction(nameof(Details), new { id = q.Entity.Id });
        }

        // GET: Question/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Question
                .Include(x => x.QuestionTags)
                .ThenInclude(x => x.Tag)
                .SingleOrDefaultAsync(m => m.Id == id);

            var currentUser = _userManager.GetUserAsync(User).Result;
            if (question == null || question.AuthorId != currentUser.Id && !_userManager.IsInRoleAsync(currentUser, Roles.ADMINISTRATOR.ToString()).Result)
            {
                return NotFound();
            }
            return View(new EditViewModel(question));
        }

        // POST: Question/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EditViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }

            var tagNames = _tagController.ValidateParseTags(vm.Tags, ModelState);

            if (_context.Question.Any(x => x.Id != id && x.Title == vm.Title.Trim()))
            {
                ModelState.AddModelError("Title", "A question with that title already exists");
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var question = await _context.Question
                .Include(x => x.QuestionTags)
                .ThenInclude(x => x.Tag)
                .SingleOrDefaultAsync(m => m.Id == id);

            var currentUser = _userManager.GetUserAsync(User).Result;
            if (question == null || question.AuthorId != currentUser.Id && !_userManager.IsInRoleAsync(currentUser, Roles.ADMINISTRATOR.ToString()).Result)
            {
                return NotFound();
            }

            var initialTitle = question.Title;
            var initialContent = question.Content;

            question.Title = vm.Title.Trim();
            question.Content = vm.Content.Trim();
            question.EditDate = DateTime.Now;

            QuestionEdit edit = new QuestionEdit
            {
                Id = Guid.NewGuid().ToString(),
                QuestionId = question.Id,
                EditorId = currentUser.Id,
            };

            bool editMade = false;

            if (!initialTitle.Equals(question.Title))
            {
                edit.NewTitle = question.Title;

QAWebsite/Views/Home/About.cshtml
<style>
    .rounded-circle {
        border-radius: 100px;
        max-height: 200px;
        max-width: 200px;
    }
</style>

<!-- Team Members Row -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="my-4">Our Team</h2>
    </div>
    <div class="col-lg-4 col-sm-8 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/1.jpg" alt="">
        <h3>
            Ofer Nitka-Nakash
            <small>Team Leader</small>
        </h3>
        <p>Concordia University student in the Software Engineering Co-op program with an interest in various fields.</p>
    </div>
    <div class="col-lg-4 col-sm-8 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/2.jpg" alt="">
        <h3>
            Mike Salib
            <small>Dispute Manager</small>
        </h3>
        <p>A full time Software Engineering student at Concordia University, for more information <a href="http://www.MikeSalib.com">CLICK HERE</a></p>
    </div>
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/3.jpg" alt="">
        <h3>
            Philip Kyres
            <small>Team Member</small>
        </h3>
        <p>I am currently enrolled in Software Engineering Co-op at Concordia University. Graduated from Dawson College with a Computer Science technical DEC.</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/4.jpg" alt="">
        <h3>
            Rafik Ifrani
            <small>Team Member</small>
        </h3>
        <p>A Software Engineer student in Co-Op at Concordia. I have completed a technical degree in computer science at Dawson before university</p>
    </div>
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/5.jpg" alt="">
        <h3>
            Bradley Laguerre
            <small>Team Member</small>
        </h3>
        <p>A 3rd year Computer Engineering student at Concordia University. Graduated from Jean-de-Brebeuf in health sciences. Practice sports such as ice hockey and basketball and loves watching tv series.</p>
    </div>
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/6.jpg" alt="">
        <h3>
            Rosa Phung
            <small>Team Member</small>
        </h3>
        <p>Currently enrolled as a full time Software Engineer at Concordia University</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/7.jpg" alt="">
        <h3>
            Chris Dubuc-Pesetti
            <small>Team Member</small>
        </h3>
        <p>I'm a full-time student in my 2nd year of Computer Engineering, graduated from John Abbott College with a degree in Applied Physics Technologies (career program). I'm a huge nerd who loves video games, books and anime</p>
    </div>
    <div class="col-lg-4 col-sm-6 text-center mb-4">
        <img class="rounded-circle" src="~/images/avatar/8.jpg" alt="">
        <h3>
            Vatika Prasad
            <small>Team Member</small>
        </h3>
        <p>Currently a full time student in Software Engineering COOP/Industrial experience program. Looking for summer 2018 internship. I got my DEC from Vanier College in Pure and Applied Sciences. Interested particularly in Game development and Android Development</p>
    </div>
</div>

QAWebsite/Views/Home/Contact.cshtml
<h2>Contact Details</h2>
<h4>Headquarters Address:</h4>
<div class="container">
    <address>
        <i>Sir George Williams Campus<br />
        1455 De Maisonneuve Blvd. W.<br />
        Montreal, Quebec, Canada<br />
        Postal Code: H3G 1M8<br />
        Phone: 514-848-2424</i>
    </address>
    <div id="googleMap" style="width:100vh;height:60vh;"></div>

    <script>
        function myMap() {
            var position = new google.maps.LatLng(45.4973, -73.5790);
            var mapProp = {
                center: position,
                zoom: 16,
            };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            var marker = new google.maps.Marker({
                position: position,
                map: map,
                title: 'Concordia University'
            });
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5kp9t9mVSktAHIN2W-M5VF4T4hnoYX5w&callback=myMap"></script>

    <address  id="contactText"><i>
    <strong>
        <br />Please contact the website administrator via e-mail if experiencing any issues related to account inquiries or website navigation.
    </strong><br />
    <strong>Website Admin can be contacted at:</strong>
    </i> <a href="mailto:Support@QAWebsite.com">QAWebsite341@gmail.com</a><br />
    </address>
</div>

QAWebsite/Views/Home/Index.cshtml
@model IEnumerable<QAWebsite.Models.QuestionViewModels.IndexViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container searchpad">
    <div class="row text-center">
        <h1 class="homeTitle">QAWebsite</h1>
        <br><br>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2 class="homeHeading">Happening Now</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Rating)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreationDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreationDate)
                        </td>
                        <td width="75%">
                            <a asp-controller="Question" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
@*    <div class="col-md-3">
        <h2>Top Contributors</h2>
        <ol>
            <li>CONTRIBUTOR</li>
            <li>CONTRIBUTOR</li>
            <li>CONTRIBUTOR</li>
        </ol>
        <h2>Highest Rated Questions</h2>
        <ol>
            <li>QUESTION</li>
            <li>QUESTION</li>
            <li>QUESTION</li>
        </ol>
    </div>*@
</div>