QAWebsite/Controllers/FlagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QAWebsite.Data;
using QAWebsite.Models.Enums;
using QAWebsite.Models.QuestionModels;
using QAWebsite.Models.QuestionViewModels;
using QAWebsite.Models.UserModels;

namespace QAWebsite.Controllers
{
    [Authorize]
    public class FlagsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FlagsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        #region User Functionality
        // GET: Flags/Create
        public IActionResult Create(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flagModel = new FlagViewModel(id);

            return View(flagModel);
        }

        // POST: Flags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FlagViewModel fm)
        {
            if (ModelState.IsValid)
            {
                var flag = new Flag
                {
                    Id = Guid.NewGuid().ToString(),
                    Reason = (int)fm.SelectedReason,
                    Content = fm.Content,
                    CreationDate = DateTime.Now,
                    QuestionId = fm.QuestionId,
                    AuthorId = _userManager.GetUserId(User)
                };

                _context.Add(flag);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Question", flag.Id);
            }
            return View(fm);
        }
        #endregion

        #region Admin Functionality
        // GET: Flags
        public async Task<IActionResult> Index()
        {
            if (!this.IsAdmin())
                return NotFound();

            var flags = await _context.Flag.ToListAsync();

            return View(this.GetFlagViewModel(flags));
        }

        public async Task<IActionResult> FlagsByQuestion(string id)
        {
            if (!this.IsAdmin() || id == null)
                return NotFound();
                
            var flags = await _context.Flag.Where(f => f.QuestionId == id).ToListAsync();           

            return View("Index", this.GetFlagViewModel(flags));
        }

        private List<FlagViewModel> GetFlagViewModel(List<Flag> flags)
        {
            List<FlagViewModel> flagList = new List<FlagViewModel>();

            flags.ForEach(f =>
            {
                flagList.Add(new FlagViewModel(f, f.QuestionId, _context.Users.Where(u => u.Id == f.AuthorId).Select(x => x.UserName).SingleOrDefault()));
            });

            return flagList;
        }

        // GET: Flags/Details/5
        public async Task<IActionResult> Details(string id)
        {

            if (id == null || !this.IsAdmin())
            {
                return NotFound();
            }

            var flag = await _context.Flag
                .SingleOrDefaultAsync(m => m.Id == id);

            if (flag == null)
            {
                return NotFound();
            }

            var fvm = new FlagViewModel(flag, flag.QuestionId, _context.Users.Where(u => u.Id == flag.AuthorId).Select(x => x.UserName).SingleOrDefault());

            return View(fvm);
        }        
 
        // GET: Flags/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || !this.IsAdmin())
            {
                return NotFound();
            }

            var flag = await _context.Flag
                .SingleOrDefaultAsync(m => m.Id == id);
            if (flag == null)
            {
                return NotFound();
            }
            var fvm = new FlagViewModel(flag, flag.QuestionId, _context.Users.Where(u => u.Id == flag.AuthorId).Select(x => x.UserName).SingleOrDefault());

            return View(fvm);
        }

        // POST: Flags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (id == null || !this.IsAdmin())
            {
                return NotFound();
            }

            var flag = await _context.Flag.SingleOrDefaultAsync(m => m.Id == id);
            _context.Flag.Remove(flag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        private bool FlagExists(string id)
        {
            return _context.Flag.Any(e => e.Id == id);
        }
        private bool IsAdmin()
        {          
           return _userManager.IsInRoleAsync(_userManager.GetUserAsync(User).Result, Roles.ADMINISTRATOR.ToString()).Result;
        }
    }
    #endregion
}

QAWebsite/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using QAWebsite.Data;
using QAWebsite.Models.QuestionModels;
using QAWebsite.Extensions;
using QAWebsite.Models.QuestionViewModels;
using QAWebsite.Models.Enums;

namespace QAWebsite.Controllers
{
    public class TagController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TagController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tag
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tag.Include(x => x.QuestionTags)
                .Select(t => new TagViewModel(t, t.QuestionTags.Count))
                .ToListAsync());
        }

        public IEnumerable<string> ValidateParseTags(string commaDelimitedTags, ModelStateDictionary modelState)
        {
            if (string.IsNullOrWhiteSpace(commaDelimitedTags))
            {
                return Enumerable.Empty<string>();
            }

            var tags = commaDelimitedTags.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(x => x.Trim()).Where(s => s != string.Empty).Distinct();

            // Validate tags? If bad, invalidate the model state
            string tag = tags.FirstOrDefault(x => x.Length > 35);
            if (tag != null)
            {
                modelState.AddModelError("Tags", $"The tag \n'{tag}'\nis too long; the maximum length is 35 characters.");
            }

            return tags;
        }

        public async Task CreateQuestionTags(Question question, IEnumerable<string> tagNames)
        {
            foreach (var name in tagNames)
            {
                Tag tag = new Tag { Id = Guid.NewGuid().ToString(), Name = name };
                tag = _context.Tag.AddIfNotExists(tag, t => t.Name == name);
                _context.QuestionTag.Add(new QuestionTag { Question = question, Tag = tag });
            }

            await _context.SaveChangesAsync();
        }

        public async Task UpdateQuestionTags(Question existingQuestion, IEnumerable<string> newTagNames)
        {
            var names = new HashSet<string>(newTagNames);
            var toRemove = existingQuestion.QuestionTags.Where(x => !names.Contains(x.Tag.Name));
            _context.QuestionTag.RemoveRange(toRemove);

            await CreateQuestionTags(existingQuestion, names.Except(existingQuestion.QuestionTags.Select(x => x.Tag.Name)));
        }

        // GET: Tag/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || !User.IsInRole(Roles.ADMINISTRATOR.ToString()))
            {
                return NotFound();
            }

            var tag = await _context.Tag
                .SingleOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tag/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (id == null || !User.IsInRole(Roles.ADMINISTRATOR.ToString()))
            {
                return NotFound();
            }

            var tag = await _context.Tag.SingleOrDefaultAsync(m => m.Id == id);
            _context.Tag.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(string id)
        {
            return _context.Tag.Any(e => e.Id == id);
        }
    }
}

QAWebsite/Views/Shared/_Layout.cshtml
@using QAWebsite.Models.Enums
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QAWebsite</title>

    <environment>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">QAWebsite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Question" asp-action="Index">Questions</a></li>
                    <li><a asp-area="" asp-controller="Tag" asp-action="Index">Tags</a></li>
                    @if(User.Identity.IsAuthenticated && User.IsInRole(@Roles.ADMINISTRATOR.ToString()))
                    {    
                        <li><a asp-area="" asp-controller="Flags" asp-action="Index">Flags</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li>
                        <form method="get" action="@Url.Action("Search", "Question")" class="navbar-form navbar-left">
                            <div class="input-group">
                                <input type="text" name="search" id="search" class="form-control" />
                                <span class="input-group-btn"><button type="submit" class="btn btn-default">Search</button></span>
                            </div>
                        </form>
                    </li>
                </ul>

                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - QAWebsite</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>